### ISSUE TITLE
Crashing under Win7 x64

### ISSUE THREAD

**Issue by fafayqa** [epicabsol/LDDCollada#3]
I managed to FINALLY compile it (it was compiled into Debug folder) with Visual Studio Express 2015 for Windows Desktop, but when I try to run it from the command line - besides it is not creating INI file after I provide path to extracted db folder, it crashes with this in CMD window:

```
C:\Users\1\Desktop\LDDCollada-master\bin\Debug>lddcollada test.lxf
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\10039.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\10509.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\10677.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\10679.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\10888.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\11145.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\11146.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\11147.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\11767.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\11938.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\12202.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\12896.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\16360.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\16709.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\20379.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\20841.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\20844.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\21019.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\21980.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\24319.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\24323.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\26910.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\26912.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\26913.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\332401.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\41475.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\41986.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\46564.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\50163.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\53787.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\53793.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\54690.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\54754.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\54824.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\54869.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\54870.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\55804.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\55805.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\55806.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\57796.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\58118.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\58119.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\58120.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\58121.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\58122.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\58123.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\59225.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\59226.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\601948.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\61100.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\61639.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\61903.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\61927.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\62606.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\63208.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\64022.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\64414.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\64422.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\64452.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\64786.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\73037.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\73081.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\73200.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\73537.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\73587.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\73603.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\73983.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\74499.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\74643.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\74741.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\75172.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\75348.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\75547.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\75998.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\76019.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\76147.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\76382.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\76407.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\76514.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\76537.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\84637.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\84638.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\84943.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\85043.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\85049.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\87958.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\87959.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\91992.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\91994.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\92693.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\92712.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\92817.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\92818.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\92819.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\92820.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\92821.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\95292.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\95648.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\95658.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\97149.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\98159.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\98161.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\98496.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\99415.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\99455.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\99498.lxfml
Loading assembly C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Assemblies\99499.lxfml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10040.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10042.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10048.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10049.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10050.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10051.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10052.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10053.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10054.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10055.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10056.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10057.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10058.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10065.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10066.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10067.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10089.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10095.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10113.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10124.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10126.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10127.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10128.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10130.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10152.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10154.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10164.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10166.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10168.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10169.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10170.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10172.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10173.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10177.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10178.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10183.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10187.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10190.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10197.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10201.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10202.xml
Loading primitive C:\Users\1\AppData\Roaming\LEGO Company\LEGO Digital Designer\db\Primitives\10202.xmlORIGINAL

Unhandled Exception: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at LDDCollada.LDDDB.Load(String partDBPath, Boolean copyTextures, Boolean colorizeTextures, Boolean duplicateDecalBricks, Boolean flipTextureCoordinates) in C:\Users\1\Desktop\LDDCollada-master\LDDCollada.Shared\LDDDB.cs:line 43
   at LDDCollada.Program.Main(String[] args) in C:\Users\1\Desktop\LDDCollada-master\Program.cs:line 41
```
Like there is literally JUST ONE BRICK in the model lxf, yet your app seems to go ABSOLUTELY UNNECESSARILY thru all the bricks in the LDD for some reason (or that is how ti looks to me) only to crashing along the way...gee, wish I could programm in CPP instead of JAVA, as this seems to be so trivial!

Like you first check which brickIDs are in the actual model and process only those, you do not go listing all the bricks in the LDD - why??????

**Comment by fafayqa** [comment]
OK, so after I looked at the C# code syntax it looks pretty similar to my JAVA, thus I ended up modifying your code (fingers crossed )! :-))))
First of all, I added if() statement to section where it lists Primitives: as I am able modding LDD bricks (like adding my new ones, or adding decoration to nondecorate dones etc.), I have habit of duplicating original XML of the brick I am modding, so if I need I can return to the original still.  I do it bz changing the XML extension to .xmlORIGINAL. So you app was crashing because of that. I changed it to this:

LDDDB.cs
```
            // Load which primitives exist
            PrimitiveCache = new Dictionary<string, Geometry>();
            foreach (string filename in Directory.EnumerateFiles(Path.Combine(PartDBPath, "Primitives")))
            {
                if (System.IO.Path.GetExtension(filename) == "xml") {
                    Console.WriteLine("Loading primitive " + filename);
                    PrimitiveCache.Add(System.IO.Path.GetFileNameWithoutExtension(filename), null);
                }
            }
```

...and at the end of the file/code I had to modify strings in string array float "." to "," which is the correct one on my system (Windows 7 Ultimate x64 SP2 Slovak), else it would end crashing once again in errors.

LDDDB.cs
```
public static Matrix DecodeLDDTransform(string input)
        {
            string[] parts = input.Split(',');

            /*Console.WriteLine("=====================================");
            Console.WriteLine(string.Join(", ", parts));
            Console.WriteLine("=====================================");*/
            
            return new Matrix(Single.Parse(parts[0].Replace(".", ",")), Single.Parse(parts[1].Replace(".", ",")), Single.Parse(parts[2].Replace(".", ",")), 0.0f,
                Single.Parse(parts[3].Replace(".", ",")), Single.Parse(parts[4].Replace(".", ",")), Single.Parse(parts[5].Replace(".", ",")), 0.0f,
                Single.Parse(parts[6].Replace(".", ",")), Single.Parse(parts[7].Replace(".", ",")), Single.Parse(parts[8].Replace(".", ",")), 0.0f,
                Single.Parse(parts[9].Replace(".", ",")), Single.Parse(parts[10].Replace(".", ",")), Single.Parse(parts[11].Replace(".", ",")), 1.0f);
        }
```
 Also I do not understand why did you place writing settings to INI (path to extracted DB) at the end of your code?
Like if it crash along the way before it reaches the write function it would be never written down, as it was the case - so I changed it to this (also I do not wanted to permanently selecting the DB folder for the app, so I hardwired the path right away as default and just let the app check if the path exists, and if not, only then prompt for the path, as you can see):

Program.cs
```
            Config = new INIFile(Path.Combine(Path.GetDirectoryName(typeof(Program).Assembly.Location), INI_FILENAME));
            string partDBPath = Config.GetValueOrDefault("LDDCollada", "PartDBPath", null);
            partDBPath = "C:\\Users\\1\\AppData\\Roaming\\LEGO Company\\LEGO Digital Designer\\db";
            Config.SetValue("LDDCollada", "PartDBPath", partDBPath);
            Config.Write(Path.Combine(Path.GetDirectoryName(typeof(Program).Assembly.Location), INI_FILENAME));

            // Make sure we have the folder to the part DB
            if (!Directory.Exists(partDBPath))
            {
                FolderBrowserDialog browser = new FolderBrowserDialog();
                if (browser.ShowDialog() == DialogResult.OK)
                {
                    partDBPath = browser.SelectedPath;
                    Config.SetValue("LDDCollada", "PartDBPath", partDBPath);
                }
                else
                {
                    return;
                }
            }

            LDDDB.Load(partDBPath, true, true, true, true);

            foreach (string filename in args)
            {
                if (filename.EndsWith(".lxfml", StringComparison.InvariantCultureIgnoreCase))
                {
                    DAEConversion.ConvertLXFML(filename);
                }
                else if (filename.EndsWith(".lxf", StringComparison.InvariantCultureIgnoreCase))
                {
                    DAEConversion.ConvertLXF(filename);
                }
                else
                {
                    Console.WriteLine("[WARNING]: Filename does not end in .lxf or .lxfml: '" + filename + "'!");
                }
            }
```

So only now it actually finally works as it should on Windows machine! :-)))
At the moment tested only for the single brick model, will test later for full-house.
Also I still do not get why do you checking assembliesa and primitives right away beforehand? If I do not find it necesarry, I will change it to do it only after it checked what bricks are present in the model itself and only then make that listing (if it has any reason at all).
